package commandlinetoolkit

type CLIERROR int32

const CLI_NO_ERROR CLIERROR = 1
const CLI_UNKOWNINPUT_ERROR CLIERROR = 2
const CLI_INVALIDINPUT_ERROR CLIERROR = 4
const CLI_REQARGUMENTNOTFOUND_ERROR CLIERROR = 8
const CLI_WRONGDATA_ERROR CLIERROR = 16
const CLI_HELPEXIT_ERROR CLIERROR = 32
const CLI_ARGUMENTNOTFOUND_ERROR CLIERROR = 64
